//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYMandYOGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string mob { get; set; }
        public string email { get; set; }
        public string msg { get; set; }
        public string contactdate { get; set; }
    }
}
